#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.instance.prefer-ip-address=true
#
#server.port=8761
#
#server.application.name=discovery-server

spring.application.name=discovery-server
server.port=8761

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false