server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3307/order_service
    username: root
    password: ikTree1234#

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true